version: '3.8'

services:
  app:
    build:
      context: ../
      dockerfile: Docker/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    container_name: node-app
    networks:
      - app-network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    container_name: nginx-proxy
    networks:
      - app-network

networks:
  app-network:
    driver: bridge